### ISSUE TITLE
Mouse Cursor Visible

### ISSUE THREAD

**Issue by mistborne** [haltepunkt/ControllerOverlay#1]
When ControllerOverlay is enabled, the mouse cursor is visible.  If you disable ControllerOverlay, the mouse hides as it should.

**Comment by haltepunkt** [comment]
This is a known bug, quite likely caused by BakkesMod itself.

**Comment by haltepunkt** [comment]
The latest version of BakkesMod should fix this issue. Can you confirm?

**Comment by mistborne** [comment]
Looks good, overlay loads and no cursor.  Thanks!
