### ISSUE TITLE
TitleBar setting not registering in Bakkesmod console

### ISSUE THREAD

**Issue by GreezyJR** [haltepunkt/ControllerOverlay#2]
I tried the auto install, and the manual install and the option is just not showing up in Bakkesmod.
Did it on a fresh install to make sure I am not crazy as well.

**Comment by haltepunkt** [comment]
The latest version has not yet been made available at BakkesPlugins.

I'm sorry for causing confusion by adding the new description and release notes early.

**Comment by haltepunkt** [comment]
The latest version has not yet been made available by BakkesPlugins.

I'm sorry for causing confusion by adding the new description and release notes early.
