### ISSUE TITLE
how do i turn it off?

### ISSUE THREAD

**Issue by jdubc29** [haltepunkt/ControllerOverlay#4]
when i try to press the X button to take it away it doesnt work for some reason

**Comment by jdubc29** [comment]
> _No description provided._

when i try to press the x button to take it away it doesnt work for some reason

**Comment by Quaybevibin** [comment]
i have the same problem

**Comment by jdubc29** [comment]
> i have the same problem

yeh and now its forever up in the corner and i cant see quick chat

**Comment by Quaybevibin** [comment]
exactly

**Comment by AshanRice** [comment]
OK i found the fix. Go to Bakkes Mod, Plugins in the top, Plugin Manager, Open Plugin Manager, uncheck controller overlay
