### ISSUE TITLE
Doesn't show in plugins in bakkesmod in-game

### ISSUE THREAD

**Issue by fastdraakje** [haltepunkt/ControllerOverlay#6]
I wanted to change the settings and was looking for the controller overlay in plugins, but it doesn't show? Am i looking at the wrong place or is this bugged with the new update? (it is working but i can't change any settings)

**Comment by Orangenal-name** [comment]
Bro. Check the BakkesPlugins page.

**Comment by NeonSpaceTurtle** [comment]
I was struggling to enable it for a while too. Go to Plugins>Open pluginmanager>tick the 'Loaded' box for Controller Overlay.
